shell /opt/homebrew/bin/fish
include ./themes/solarized
include ./keybinds.conf

#LAYOUT
enabled_layouts tall:bias=50;full_size=1;mirrored=false

# WINDOW
window_padding_width 10

# CURSOR
cursor_shape beam
cursor_trail 1

# OPACITY
#background_blur 97
#background_opacity 0.96

# BEGIN_KITTY_FONTS
font_size 18
font_family      family='Maple Mono NF' postscript_name=MapleMono-NF-Light
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS






